apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: story-app
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: pkpavan14/story-app-backend:
          ports:
            - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: story-app
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 32000
