apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: story-app
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: pkpavan14/story-app-frontend:v3
          ports:
            - containerPort: 5173

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: story-app
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 5173
      targetPort: 5173
      nodePort: 31000
