apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: story-app
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem   
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/db
